Created CreatePost component
UNLV-CS472-672/2024-S-GROUP1-Roadwatch pull request #120
Opened 2024-04-11 22:31 UTC by trevortippery

## Description
For this PR, I created the CreatePost component that will be used in the Community Page with a click of a button.

## Related Issue
This PR closes #112 and should be used in #110.

## Type of Changes
Please select the relevant option:
- [ ] Bug fix
- [x] New feature
- [x] Enhancement
- [ ] Documentation update
- [ ] Other (please specify)
      
The CreatePost uses Material UI's dialog component, slide transition, and floating action buttons (FAB).

References to Material UI:
https://mui.com/material-ui/react-dialog/#full-screen-dialogs
https://mui.com/material-ui/react-floating-action-button/

## Things to Update
Please add any features, buttons, or pages that might need updating in the future:
- [ ] Button Functionality 
- [x] Code Documentation 
- [x] Mobile Responsiveness 
- [ ] Code testing 
- [x] Other (Sending data to the backend (refactoring), and swipe down feature to close the dialog)

## Screenshots 
Inital button to open CreatePost component
<img width="400" alt="Screenshot 2024-04-11 at 3 27 47 PM" src="https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/69101935/d6e242d1-ee6b-4511-b0c7-8421f58fe3ba">

CreatePost component
<img width="337" alt="Screenshot 2024-04-11 at 3 28 05 PM" src="https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/69101935/d2526767-20bf-4ad5-8033-18adec2a893c">

## Additional Notes
ChatGPT was used to refactor redundancy of Material UI FABs. Create the feature that all data fields and a choice of a marker needs to be selected before the post button will work. I did not include an error message popup when the text fields are empty, and I did not include the swipe down feature to close the dialog. For now, data points are printed to console. Testing was done on the community page.

Link to ChatGPT conversation: https://chat.openai.com/share/02544161-0bdf-4b7e-8644-18d39aa174ff

2024-04-11 22:41 UTC, dafneMena requested changes
Hi the component looks great! 

I noticed that you added the there dots '...' as a marker but I thought that option was getting removed since we weren't exactly sure what it would point to. I might be wrong though? 

Maybe we can check with the team before merging that way we can delete it if needed!

2024-04-11 22:51 UTC, trevortippery commented
> Hi the component looks great!
> 
> I noticed that you added the there dots '...' as a marker but I thought that option was getting removed since we weren't exactly sure what it would point to. I might be wrong though?
> 
> Maybe we can check with the team before merging that way we can delete it if needed!

Yeah should be an easy fix. I completely forgot. Thank you for noticing.

2024-04-11 22:55 UTC, KingJordan152 commented
> Hi the component looks great!
> 
> I noticed that you added the there dots '...' as a marker but I thought that option was getting removed since we weren't exactly sure what it would point to. I might be wrong though?
> 
> Maybe we can check with the team before merging that way we can delete it if needed!

I think we can go ahead and delete that. The options provided are good enough for now.

2024-04-11 23:01 UTC, trevortippery commented
Etc marker has been removed from the code.

2024-04-11 23:02 UTC, KingJordan152 requested changes
Overall, this component looks super nice, Trevor. Great work on making it look very similar to the Figma!

I have a few requests regarding initializing fields with data automatically and code convention. Also, please fix the conflict you have in `client/src/components/index.ts`.

Other than that, great work!

2024-04-11 23:02 UTC, KingJordan152 commented on client/src/components/CreatePost/CreatePost.tsx
> +        <React.Fragment>
`React.Framgment` is an old React pattern. You can just use empty tags `<></>`.

2024-04-11 23:05 UTC, Aligary approved these changes
Great work, Trevor! Well update sending the post to the backend when it's ready.

2024-04-12 00:03 UTC, dafneMena approved these changes
Looks good, thanks!

2024-04-12 03:13 UTC, Linkaloo approved these changes

2024-04-12 05:07 UTC, trevortippery commented on client/src/components/CreatePost/CreatePost.tsx
> +        setDate('');
Yeah absolutely.

2024-04-12 05:50 UTC, trevortippery commented
The changes should be implemented now. I used geolocation and prompt for the user permission to get their current location. The location should include their latitude and longitude.

2024-04-15 02:42 UTC, KingJordan152 commented
@trevortippery I just learned you can implement the swiping feature from iOS using this MUI component: 
https://mui.com/material-ui/react-drawer/#swipeable

Maybe you should look into implementing this before merging this component in?

2024-04-15 03:04 UTC, KingJordan152 requested changes
Thank you for implementing my changes. This looks great, thank you for your hard work.

I left one more request for you regarding the swiping-to-dismiss feature. I just found an MUI component that does that for you. If you could implement that in this component that would be perfect!

2024-04-15 03:04 UTC, KingJordan152 commented on client/src/components/CreatePost/CreatePost.tsx
> +        <>
I think you could replace this fragment with this component from MUI: https://mui.com/material-ui/react-drawer/#swipeable

2024-04-15 05:22 UTC, trevortippery commented
Swipe feature for mobile view should be implemented. @KingJordan152

2024-04-15 16:57 UTC, KingJordan152 approved these changes
This looks amazing. Thank you for implementing the swipe feature. Approved!

2024-04-15 17:01 UTC, merged