Email service
UNLV-CS472-672/2024-S-GROUP1-Roadwatch pull request #121
Opened 2024-04-14 23:02 UTC by Linkaloo

## Description
Provides endpoints for a user to state they forgot their password and so they can set a new password.
Provides mutations in the client to use and creates a simple page to apply a new password to the user.

## Related Issue
closes #103 

## Type of Changes
Please select the relevant option:
- [ ] Bug fix
- [x] New feature
- [x] Enhancement
- [ ] Documentation update
- [ ] Other (please specify)

## Things to Update
Please add any features, buttons, or pages that might need updating in the future:
- [ ] Button Functunality 
- [ ] Code Documentation 
- [x] Mobile Responsiveness 
- [x] Code testing 
- [ ] Other (please specify)

## Screenshots 
Email:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/9b2a5551-4c39-4291-9eca-cb534da09cd1)

Reset password page:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/d400bc74-ed94-4ae0-94d1-f8ec85af6577)

## Additional Notes
I made a very simplistic password change page because I know Trevor is working on something. I wasn't sure what idea to go with this at first so just decided to run with this one:

Trevor made a reset password component, which is really a forgot password component as you ask for the email. That should be its own page that calls the forgot password endpoint. The verify email we will leave out for now and maybe instead use that for when a user adds their email. Then this will be the actual page where a password is changed and there is already a type of authentication done to ensure that it is the correct user.

2024-04-15 03:09 UTC, KingJordan152 requested changes
This looks beyond amazing. Terrific work, Josh!

I left one comment regarding the `baseUrl` in the API slice. I believe that should be changed back to what you had previously. 

Also, don't forget to send us the send grid API key!

2024-04-15 03:09 UTC, KingJordan152 commented on client/src/store/api/api.slice.ts
> +    baseUrl: 'http://localhost:3000/api',
I think this should be changed back to `import.meta.env.VITE_API_BASE_URL`.

2024-04-15 21:55 UTC, Aligary approved these changes
Thanks, Josh 👍🏽 Everything looks well

2024-04-16 18:07 UTC, dafneMena approved these changes
This looks amazing! Love the layout and design, you nailed it!
I noticed you sent the grid API key to our emails so thank you for that as well.

2024-04-16 22:13 UTC, KingJordan152 approved these changes
Everything looks good. Thank you for implementing my request. Approved!

2024-04-17 18:26 UTC, merged